### ISSUE TITLE
Add extra info to message when a JS Fiddle has a redundant <html>,<head>,<body>

### ISSUE THREAD

**Issue by cvrebert** [cvrebert/lmvtfy#115]
Explain that the HTML panel's content is shoved into a `<body>` so it's not valid to include such tags.
Refs twbs/bootstrap#17744.

**Comment by cvrebert** [comment]
Experiment 1: `<body>`: http://jsfiddle.net/a2oLyym6/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/a2oLyym6/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 31, column 3 thru column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 35, column 1 thru column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Experiment 2: `<html>`: http://jsfiddle.net/a2oLyym6/1/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/a2oLyym6/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 31, column 3 thru column 8: Stray start tag ```` html ````.
* line 32, column 5 thru column 10: Stray start tag ```` head ````.
* line 32, column 5 thru column 17: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 32, column 29 thru column 35: Stray end tag ```` head ````.
* line 33, column 1 thru column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 38, column 1 thru column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
More informative errors?
http://jsfiddle.net/a2oLyym6/
http://jsfiddle.net/a2oLyym6/1/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/a2oLyym6/1/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* JSFiddle inserts the contents of its "HTML" pane within ```` <body>...</body> ```` tags, so you cannot include your own ```` <html> ````, ```` <head> ````, or ```` <body> ```` tags in your JSFiddle.
* line 31, column 3 thru column 8: Stray start tag ```` html ````.
* line 32, column 5 thru column 10: Stray start tag ```` head ````.
* line 32, column 5 thru column 17: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 32, column 29 thru column 35: Stray end tag ```` head ````.
* line 33, column 1 thru column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 38, column 1 thru column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/a2oLyym6/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* JSFiddle inserts the contents of its "HTML" pane within ```` <body>...</body> ```` tags, so you cannot include your own ```` <body> ```` tag in your JSFiddle.
* line 31, column 3 thru column 8: Start tag ```` body ```` seen but an element of the same type was already open.
* line 35, column 1 thru column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Great success.
