### ISSUE TITLE
Bootlint entity too large bug?

### ISSUE THREAD

**Issue by cvrebert** [cvrebert/lmvtfy#119]
Example: http://jsfiddle.net/9waquk0b/
Refs https://github.com/twbs/bootstrap/issues/17035

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/9waquk0b/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [XX0](https://github.com/twbs/bootlint/wiki/XX0): Your example is too large for Bootlint to process! Please simplify your example and make it smaller.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Are you sane now? http://jsfiddle.net/9waquk0b/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/9waquk0b/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [XX0](https://github.com/twbs/bootlint/wiki/XX0): Your example is too large for Bootlint to process! Please simplify your example and make it smaller.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Gimme debug output http://jsfiddle.net/9waquk0b/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/9waquk0b/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [XX0](https://github.com/twbs/bootlint/wiki/XX0): Your example is too large for Bootlint to process! Please simplify your example and make it smaller.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Bumped the entity size limit http://jsfiddle.net/9waquk0b/

**Comment by cvrebert** [comment]
Yup, that was it.

**Comment by cvrebert** [comment]
Final re-test: http://jsfiddle.net/9waquk0b/

**Comment by cvrebert** [comment]
Yay.
