### ISSUE TITLE
Ignore errors about bad autocomplete values

### ISSUE THREAD

**Issue by cvrebert** [cvrebert/lmvtfy#130]

**Comment by sideshowbarker** [comment]
eh? why?

**Comment by cvrebert** [comment]
Well, the thought was that it doesn't tend to break anything beyond autocomplete itself, so it's not usually germane to whatever JS/CSS bug the testcase was submitted for, kinda like the other stuff we already ignore (https://github.com/cvrebert/lmvtfy#deliberately-ignored-errors ). The fact that the spec'd values didn't validate also wasn't helping.
But since that validator bug has now been fixed, this isn't nearly as necessary anymore.
