### ISSUE TITLE
Error message from Jsfiddle + Bootstrap + No JS

### ISSUE THREAD

**Issue by Nagle** [cvrebert/lmvtfy#72]
Please see
https://github.com/twbs/bootstrap/issues/15510#issuecomment-68957262

Note that the jsfiddle in question does not use Bootstrap's jQuery plugins nor any JavaScript.

**Comment by cvrebert** [comment]
It's nontrivial to check whether examples contain any JS or not (what with inline event handler attributes, etc.), but I suppose we could special-case the contains-bootstrap.js-but-not-jQuery case, which is the common problematic one, and squelch the warning in the common non-problematic contains-neither-bootstrap.js-nor-jQuery case.

**Comment by cvrebert** [comment]
This should now not report any Bootlint errors: http://jsfiddle.net/xnjcqb9o/1/embedded/result/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://fiddle.jshell.net/xnjcqb9o/1/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 15, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Well, it doesn't make any irrelevant complaint about jQuery anymore. That's what matters.
