### ISSUE TITLE
Try to ignore non-HTML Gists

### ISSUE THREAD

**Issue by coliff** [cvrebert/lmvtfy#75]
It'd be good if lmvtfy ignored links to Gists (which are typically just text documents)

**Comment by cvrebert** [comment]
We deliberately support Gists since people have used them in the wild for examples (albeit infrequently). I could see adding a configuration option to enable/disable Gist support though. Would that be satisfactory?

**Comment by cvrebert** [comment]
Ah, I see this is in regard to https://github.com/twbs/bootstrap/issues/15758#issuecomment-75715911
The benefits outweigh the cost of some false positives, IMO.

**Comment by cvrebert** [comment]
Perhaps we should just add a simple heuristic: Only attempt to validate the Gist if it contains substrings matching `<[a-zA-Z]+>` and `</[a-zA-Z]+>` (i.e. opening and closing HTML tags)
