### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by cvrebert** [cvrebert/lmvtfy#93]
The old test issue was getting a bit long.

**Comment by cvrebert** [comment]
https://gist.github.com/mbostock/1353700

**Comment by cvrebert** [comment]
Does bl.ocks now work? http://bl.ocks.org/cvrebert/aef444eb168d79c7f350

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 4, column 9 thru line 4, column 12: Element ```` li ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 4, column 19 thru line 4, column 25: Stray end tag ```` span ````.
* line 5, column 1 thru line 5, column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 4, column 3 thru line 4, column 8: Unclosed element ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
And raw? http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 4, column 9 thru line 4, column 12: Element ```` li ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 4, column 19 thru line 4, column 25: Stray end tag ```` span ````.
* line 5, column 1 thru line 5, column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 4, column 3 thru line 4, column 8: Unclosed element ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
And with filename? http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/index.html

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 4, column 9 thru line 4, column 12: Element ```` li ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 4, column 19 thru line 4, column 25: Stray end tag ```` span ````.
* line 5, column 1 thru line 5, column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 4, column 3 thru line 4, column 8: Unclosed element ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
And at specific version? http://bl.ocks.org/cvrebert/aef444eb168d79c7f350/5f1514003f37e7663bf3fd96870431ff7981c526

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/5f1514003f37e7663bf3fd96870431ff7981c526/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 4, column 9 thru line 4, column 12: Element ```` li ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 4, column 19 thru line 4, column 25: Stray end tag ```` span ````.
* line 5, column 1 thru line 5, column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 4, column 3 thru line 4, column 8: Unclosed element ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
And raw at specific version? http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/5f1514003f37e7663bf3fd96870431ff7981c526

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/5f1514003f37e7663bf3fd96870431ff7981c526/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 4, column 9 thru line 4, column 12: Element ```` li ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 4, column 19 thru line 4, column 25: Stray end tag ```` span ````.
* line 5, column 1 thru line 5, column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 4, column 3 thru line 4, column 8: Unclosed element ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
And finally, raw at specific version with filename?
http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/5f1514003f37e7663bf3fd96870431ff7981c526/index.html

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://bl.ocks.org/cvrebert/raw/aef444eb168d79c7f350/5f1514003f37e7663bf3fd96870431ff7981c526/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 4, column 9 thru line 4, column 12: Element ```` li ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 4, column 19 thru line 4, column 25: Stray end tag ```` span ````.
* line 5, column 1 thru line 5, column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 4, column 3 thru line 4, column 8: Unclosed element ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
And out of curiosity:
http://bl.ocks.org/mbostock/1353700/190ad80b4eb9c5e6daa7d4f210d263cbfb6db675

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://bl.ocks.org/mbostock/raw/1353700/190ad80b4eb9c5e6daa7d4f210d263cbfb6db675/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W001](https://github.com/twbs/bootlint/wiki/W001): `<head>` is missing UTF-8 charset `<meta>` tag
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Do pastebins now work? http://pastebin.com/0WTN219r

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://pastebin.com/0WTN219r), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 10, column 15 thru line 10, column 20: End tag ```` div ```` seen, but there were open elements.
* line 10, column 6 thru line 10, column 11: Unclosed element ```` span ````.
* line 10, column 21 thru line 10, column 27: Stray end tag ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Do you also accept raw pastebin URLs? http://pastebin.com/raw.php?i=0WTN219r

**Comment by cvrebert** [comment]
What about raw pastebins?
http://pastebin.com/raw.php?i=0WTN219r

**Comment by cvrebert** [comment]
Let's try that again: http://pastebin.com/raw.php?i=0WTN219r

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://pastebin.com/0WTN219r), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 10, column 15 thru line 10, column 20: End tag ```` div ```` seen, but there were open elements.
* line 10, column 6 thru line 10, column 11: Unclosed element ```` span ````.
* line 10, column 21 thru line 10, column 27: Stray end tag ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dandv** [comment]
http://jsbin.com/vivuxumana/1/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @dandv!

You appear to have posted a live example (http://jsbin.com/vivuxumana/1/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness
* line 8, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.
* line 11, column 3: [W007](https://github.com/twbs/bootlint/wiki/W007): Found one or more `<button>`s missing a `type` attribute.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by dandv** [comment]
http://jsbin.com/vivuxumana/3/edit

**Comment by dandv** [comment]
Does the bot post anything if there are no errors?

**Comment by cvrebert** [comment]
> Does the bot post anything if there are no errors?

It does not.

**Comment by cvrebert** [comment]
http://codepen.io/anon/pen/RPmbWV

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (http://codepen.io/anon/pen/RPmbWV.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 8, column 1 thru column 15: Stray doctype.
* line 9, column 1 thru column 6: Stray start tag ```` html ````.
* line 10, column 1 thru column 6: Stray start tag ```` head ````.
* line 12, column 1 thru column 118: Element ```` link ```` is missing required attribute ```` property ````.
* line 14, column 3 thru column 24: Attribute ```` charset ```` not allowed on element ```` meta ```` at this point.
* line 14, column 3 thru column 24: Element ```` meta ```` is missing one or more of the following attributes: ```` content ````, ```` itemprop ````, ```` property ````.
* line 15, column 3 thru column 9: Element ```` title ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 16, column 1 thru column 7: Stray end tag ```` head ````.
* line 17, column 1 thru column 6: Start tag ```` body ```` seen but an element of the same type was already open.
* line 29, column 1 thru column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
https://jsbin.com/vujito/edit?html,output

**Comment by cvrebert** [comment]
Let's try that once more:
https://jsbin.com/vujito/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://jsbin.com/vujito/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 16, column 6 thru column 23: The ```` align ```` attribute on the ```` div ```` element is obsolete. Use CSS instead.
* line 22, column 8 thru line 23, column 19: The ```` align ```` attribute on the ```` tr ```` element is obsolete. Use CSS instead.
* line 23, column 20 thru line 24, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 24, column 21 thru column 24: Stray end tag ```` a ````.
* line 24, column 30 thru line 25, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 25, column 26 thru column 29: Stray end tag ```` a ````.
* line 25, column 35 thru line 26, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 26, column 22 thru column 25: Stray end tag ```` a ````.
* line 26, column 31 thru line 27, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 27, column 24 thru column 27: Stray end tag ```` a ````.
* line 27, column 33 thru line 28, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 28, column 21 thru column 24: Stray end tag ```` a ````.
* line 28, column 30 thru line 29, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 29, column 24 thru column 27: Stray end tag ```` a ````.
* line 29, column 33 thru line 30, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 30, column 25 thru column 28: Stray end tag ```` a ````.
* line 30, column 34 thru line 31, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 31, column 24 thru column 27: Stray end tag ```` a ````.
* line 31, column 33 thru line 32, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 32, column 23 thru column 26: Stray end tag ```` a ````.
* line 32, column 32 thru line 33, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 33, column 28 thru column 31: Stray end tag ```` a ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
HTTPS fiddle: https://jsfiddle.net/cz7k957h/

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://fiddle.jshell.net/cz7k957h/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 36, column 9 thru column 28: Attribute ```` href ```` not allowed on element ```` span ```` at this point.
* line 39, column 7 thru column 29: Element ```` div ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 46, column 7 thru column 31: Element ```` div ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 50, column 7 thru column 41: Element ```` div ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 83, column 7 thru column 41: Element ```` div ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 117, column 7 thru column 31: Element ```` div ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 120, column 7 thru column 23: Element ```` div ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 161, column 7 thru column 31: Element ```` div ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 164, column 7 thru column 23: Element ```` div ```` not allowed as child of element ```` span ```` in this context. (Suppressing further errors from this subtree.)
* line 222, column 5 thru column 10: End tag ```` div ```` seen, but there were open elements.
* line 36, column 9 thru column 28: Unclosed element ```` span ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
https://jsbin.com/vifevequna/1/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://jsbin.com/vifevequna/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 13, column 1 thru column 49: Using the ```` meta ```` element to specify the document-wide default language is obsolete. Consider specifying the language on the root element instead.
* line 15, column 1 thru column 45: Bad value ```` Pragma ```` for attribute ```` http-equiv ```` on element ```` meta ````.
* line 16, column 1 thru column 52: Bad value ```` Cache-Control ```` for attribute ```` http-equiv ```` on element ```` meta ````.
* line 17, column 1 thru column 39: Bad value ```` Expires ```` for attribute ```` http-equiv ```` on element ```` meta ````.
* line 21, column 1 thru column 208: Attribute ```` integrity ```` not allowed on element ```` link ```` at this point.
* line 30, column 1 thru column 190: Attribute ```` integrity ```` not allowed on element ```` script ```` at this point.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment]
Still alive? https://jsbin.com/vifevequna/1/edit?html,output

**Comment by twbs-lmvtfy** [comment]
Hi @cvrebert!

You appear to have posted a live example (https://jsbin.com/vifevequna/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 13, column 1 thru column 49: Using the ```` meta ```` element to specify the document-wide default language is obsolete. Consider specifying the language on the root element instead.
* line 15, column 1 thru column 45: Bad value ```` Pragma ```` for attribute ```` http-equiv ```` on element ```` meta ````.
* line 16, column 1 thru column 52: Bad value ```` Cache-Control ```` for attribute ```` http-equiv ```` on element ```` meta ````.
* line 17, column 1 thru column 39: Bad value ```` Expires ```` for attribute ```` http-equiv ```` on element ```` meta ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)
