### ISSUE TITLE
Online validator?

### ISSUE THREAD

**Issue by dandv** [cvrebert/lmvtfy#99]
Is there an official way to validate online (like the [W3C validator](https://validator.w3.org/#validate_by_input)) without having the user comment with the URL in a `Testing` issue and the bot create a comment for each attempt?

I saw Bootlint, and also the warning that it may not run the latest version of the code.

**Comment by cvrebert** [comment]
LMVTFY = GitHub webhooks/API + W3C HTML validator + (optional) Bootlint

Are you asking how to run Bootlint outside of LMVTFY? Bootlint is a separate project; see its docs: https://github.com/twbs/bootlint#getting-started
